version: '3.7'

services:
  empty-sinatra:
    image: local/minerva
    build:
      context: .
    environment:
      - RACK_ENV=development
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./
        target: /app
